# Generated by Django 4.2.4 on 2024-02-04 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
