# Generated by Django 4.2.4 on 2024-02-04 00:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_customer_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
