# Generated by Django 4.2.4 on 2024-02-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_alter_customer_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
