# Generated by Django 4.2.4 on 2024-02-04 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_date_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date_created",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
