# Generated by Django 4.2.4 on 2024-02-04 01:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_alter_product_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
