# Generated by Django 4.2.4 on 2024-02-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_alter_order_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
