# Generated by Django 4.2.4 on 2024-02-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_alter_order_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="digital",
        ),
    ]
