# Generated by Django 4.2.4 on 2024-02-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0019_product_digital"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
