# Generated by Django 4.2.4 on 2024-02-20 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(
                default=1707160292.114927, max_length=100, null=True
            ),
        ),
    ]
