# Generated by Django 4.2.4 on 2024-02-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_alter_order_complete_alter_order_transaction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="store.order"
            ),
        ),
    ]
