# Generated by Django 4.2.4 on 2024-02-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_alter_orderitem_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image1",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
