# Generated by Django 4.2.4 on 2024-02-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_product_image1_product_image2"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image3",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
