# Generated by Django 4.2.4 on 2024-03-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_product_image3"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Out for delivery", "Out for delivery"),
                    ("Delivered", "Delivered"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
