# Generated by Django 4.2.4 on 2024-03-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Android", "Android"), ("Iphone", "Iphone")],
                max_length=200,
                null=True,
            ),
        ),
    ]
