# Generated by Django 4.2.4 on 2024-03-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Android", "Android"), ("Apple", "Apple")],
                max_length=200,
                null=True,
            ),
        ),
    ]
