# Generated by Django 4.2.4 on 2024-03-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0034_alter_order_transaction_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="product",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(blank=True, null=True, to="store.product"),
        ),
    ]
