# Generated by Django 4.2.4 on 2024-03-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0035_remove_order_product_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="product",
            field=models.ManyToManyField(blank=True, to="store.product"),
        ),
    ]
