# Generated by Django 4.2.4 on 2024-03-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0037_product_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="logo",
        ),
        migrations.AddField(
            model_name="customer",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
