# Generated by Django 4.2.4 on 2024-03-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0038_remove_product_logo_customer_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.RemoveField(
            model_name="customer",
            name="logo",
        ),
    ]
