# Generated by Django 4.2.4 on 2024-03-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0039_logo_remove_customer_logo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logo",
            old_name="logo",
            new_name="reportlogo",
        ),
    ]
