# Generated by Django 4.2.4 on 2024-03-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0040_rename_logo_logo_reportlogo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="logo",
            old_name="reportlogo",
            new_name="image",
        ),
    ]
