# Generated by Django 4.2.4 on 2024-03-16 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0041_rename_reportlogo_logo_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="logo",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
