# Generated by Django 4.2.4 on 2024-03-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0043_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
